const MOVIES = [
  { id:1, title:"Avengers: Endgame", year:2019, rating:8.4, duration:"3s 1d", genre:"action", genreLabel:"Боевик / Fantastika", language:"O'zbek tilida", quality:"HD", type:"movie", isNew:true, poster:"https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg", desc:"Avengers jamoasi Thanos ustidan g'alaba qozonish uchun oxirgi marta birlashadi. Koinotdagi yarmi yo'q qilingan mavjudotlarni qaytarish uchun ular barcha kuchlarini safarbar etadilar.", views:"2.4M", country:"AQSh" },
  { id:2, title:"Interstellar", year:2014, rating:8.6, duration:"2s 49d", genre:"fantasy", genreLabel:"Ilmiy-fantastika", language:"O'zbek tilida", quality:"UHD", type:"movie", isNew:false, poster:"https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", desc:"Insoniyatni saqlab qolish uchun bir guruh astronavtlar yulduzlaro'ti orqali sayohat qiladi. Vaqt va makon chegaralarini yengib, yangi dunyo izlaydilar.", views:"1.8M", country:"AQSh" },
  { id:3, title:"The Dark Knight", year:2008, rating:9.0, duration:"2s 32d", genre:"action", genreLabel:"Боевик / Triller", language:"O'zbek tilida", quality:"HD", type:"movie", isNew:false, poster:"https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg", desc:"Batman Gotham shahrini Joker terroridan himoya qilishi kerak. Bu kurash nafaqat jismoniy, balki ruhiy sinov ham bo'ladi.", views:"3.1M", country:"AQSh" },
  { id:4, title:"Inception", year:2010, rating:8.8, duration:"2s 28d", genre:"fantasy", genreLabel:"Ilmiy-fantastika / Triller", language:"O'zbek tilida", quality:"HD", type:"movie", isNew:false, poster:"https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg", desc:"Tush ichiga kirib sirlarni o'g'irlash san'atiga ega bo'lgan odam eng murakkab vazifani bajarishga majbur bo'ladi.", views:"2.2M", country:"AQSh" },
  { id:5, title:"Spider-Man: No Way Home", year:2021, rating:8.2, duration:"2s 28d", genre:"action", genreLabel:"Боевик / Fantastika", language:"O'zbek tilida", quality:"HD", type:"movie", isNew:true, poster:"https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg", desc:"Peter Parker ko'p olam qahramonlari va yovuzlari bilan to'qnashishi kerak bo'lgan xavfli sarguzashtga kiradi.", views:"1.9M", country:"AQSh" },
  { id:6, title:"Joker", year:2019, rating:8.4, duration:"2s 2d", genre:"drama", genreLabel:"Drama / Triller", language:"O'zbek tilida", quality:"HD", type:"movie", isNew:false, poster:"https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg", desc:"Artur Fleck jamiyat tomonidan rad etilgan komediyachi. Asta-sekin u Jokerga aylanib boradi.", views:"2.7M", country:"AQSh" },
  { id:7, title:"Parasite", year:2019, rating:8.5, duration:"2s 12d", genre:"drama", genreLabel:"Drama / Triller", language:"O'zbek tilida", quality:"HD", type:"movie", isNew:false, poster:"https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", desc:"Kam ta'minlangan oila boy oilaga sekin-asta kirib boradi. Lekin sirlar ularni kutmagan vaziyatga olib keladi.", views:"1.3M", country:"Janubiy Koreya" },
  { id:8, title:"Breaking Bad", year:2008, rating:9.5, duration:"5 mavsum", genre:"drama", genreLabel:"Drama / Triller", language:"O'zbek tilida", quality:"HD", type:"serial", isNew:false, poster:"https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg", desc:"Kimyo o'qituvchisi Walter White kasallik tashxisidan so'ng oilasini ta'minlash uchun narkobo'zanin ishlab chiqarishga kiradi.", views:"4.5M", country:"AQSh", episodes:62 },
  { id:9, title:"Game of Thrones", year:2011, rating:9.2, duration:"8 mavsum", genre:"fantasy", genreLabel:"Fantastika / Drama", language:"O'zbek tilida", quality:"UHD", type:"serial", isNew:false, poster:"https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg", desc:"Westeros qit'asida taxt uchun ko'p sulolalar o'rtasida qon to'kiladi. Ularning barchasi hukmdorlik qilishga intiladi.", views:"5.2M", country:"AQSh", episodes:73 },
  { id:10, title:"Money Heist", year:2017, rating:8.3, duration:"5 mavsum", genre:"action", genreLabel:"Боевик / Triller", language:"O'zbek tilida", quality:"HD", type:"serial", isNew:true, poster:"https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg", desc:"Profesor rahbarligida bir guruh o'g'ri Ispaniya Milliy Bankini bosib olishni rejalashtiradi.", views:"3.8M", country:"Ispaniya", episodes:41 },
  { id:11, title:"The Lion King", year:2019, rating:6.9, duration:"1s 58d", genre:"cartoon", genreLabel:"Multfilm / Drama", language:"O'zbek tilida", quality:"HD", type:"cartoon", isNew:false, poster:"https://image.tmdb.org/t/p/w500/2bXbqYdUQNa0pE6RkFQn3doZt6m.jpg", desc:"Yosh sher Simba otasining o'limidan so'ng o'z vatanini tiklash uchun kuchli safarga chiqadi.", views:"1.1M", country:"AQSh" },
  { id:12, title:"Frozen 2", year:2019, rating:6.8, duration:"1s 43d", genre:"cartoon", genreLabel:"Multfilm / Musiqa", language:"O'zbek tilida", quality:"HD", type:"cartoon", isNew:false, poster:"https://image.tmdb.org/t/p/w500/qdfARIhgpgZOBh3vfNhWS4hmSo3.jpg", desc:"Elsa va Anna sehrli o'rmonning sirini kashf qilish uchun sayohatga chiqadilar.", views:"980K", country:"AQSh" }
];
