const MOVIES = [
  { id:1, title:"Avengers: Endgame", year:2019, rating:8.4, duration:"3s 1d", genre:"action", genreLabel:"Боевик / Fantastika", language:"O'zbek tilida", quality:"HD", type:"movie", isNew:true, poster:"https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg", desc:"Avengers jamoasi Thanos ustidan g'alaba qozonish uchun oxirgi marta birlashadi. Koinotdagi yarmi yo'q qilingan mavjudotlarni qaytarish uchun ular barcha kuchlarini safarbar etadilar.", views:"2.4M", country:"AQSh" },
  { id:2, title:"Interstellar", year:2014, rating:8.6, duration:"2s 49d", genre:"fantasy", genreLabel:"Ilmiy-fantastika", language:"O'zbek tilida", quality:"UHD", type:"movie", isNew:false, poster:"https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", desc:"Insoniyatni saqlab qolish uchun bir guruh astronavtlar yulduzlaro'ti orqali sayohat qiladi. Vaqt va makon chegaralarini yengib, yangi dunyo izlaydilar.", views:"1.8M", country:"AQSh" },
  { id:3, title:"The Dark Knight", year:2008, rating:9.0, duration:"2s 32d", genre:"action", genreLabel:"Боевик / Triller", language:"O'zbek tilida", quality:"HD", type:"movie", isNew:false, poster:"https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg", desc:"Batman Gotham shahrini Joker terroridan himoya qilishi kerak. Bu kurash nafaqat jismoniy, balki ruhiy sinov ham bo'ladi.", views:"3.1M", country:"AQSh" },
  { id:4, title:"Inception", year:2010, rating:8.8, duration:"2s 28d", genre:"fantasy", genreLabel:"Ilmiy-fantastika / Triller", language:"O'zbek tilida", quality:"HD", type:"movie", isNew:false, poster:"https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg", desc:"Tush ichiga kirib sirlarni o'g'irlash san'atiga ega bo'lgan odam eng murakkab vazifani bajarishga majbur bo'ladi.", views:"2.2M", country:"AQSh" },
  { id:5, title:"Spider-Man: No Way Home", year:2021, rating:8.2, duration:"2s 28d", genre:"action", genreLabel:"Боевик / Fantastika", language:"O'zbek tilida", quality:"HD", type:"movie", isNew:true, poster:"https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg", desc:"Peter Parker ko'p olam qahramonlari va yovuzlari bilan to'qnashishi kerak bo'lgan xavfli sarguzashtga kiradi.", views:"1.9M", country:"AQSh" },
  { id:6, title:"Joker", year:2019, rating:8.4, duration:"2s 2d", genre:"drama", genreLabel:"Drama / Triller", language:"O'zbek tilida", quality:"HD", type:"movie", isNew:false, poster:"https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg", desc:"Artur Fleck jamiyat tomonidan rad etilgan komediyachi. Asta-sekin u Jokerga aylanib boradi.", views:"2.7M", country:"AQSh" },
  { id:7, title:"Parasite", year:2019, rating:8.5, duration:"2s 12d", genre:"drama", genreLabel:"Drama / Triller", language:"O'zbek tilida", quality:"HD", type:"movie", isNew:false, poster:"https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", desc:"Kam ta'minlangan oila boy oilaga sekin-asta kirib boradi. Lekin sirlar ularni kutmagan vaziyatga olib keladi.", views:"1.3M", country:"Janubiy Koreya" },
  { id:8, title:"Breaking Bad", year:2008, rating:9.5, duration:"5 mavsum", genre:"drama", genreLabel:"Drama / Triller", language:"O'zbek tilida", quality:"HD", type:"serial", isNew:false, poster:"https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg", desc:"Kimyo o'qituvchisi Walter White kasallik tashxisidan so'ng oilasini ta'minlash uchun narkobo'zanin ishlab chiqarishga kiradi.", views:"4.5M", country:"AQSh", episodes:62 },
  { id:9, title:"Game of Thrones", year:2011, rating:9.2, duration:"8 mavsum", genre:"fantasy", genreLabel:"Fantastika / Drama", language:"O'zbek tilida", quality:"UHD", type:"serial", isNew:false, poster:"https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg", desc:"Westeros qit'asida taxt uchun ko'p sulolalar o'rtasida qon to'kiladi. Ularning barchasi hukmdorlik qilishga intiladi.", views:"5.2M", country:"AQSh", episodes:73 },
  { id:10, title:"Money Heist", year:2017, rating:8.3, duration:"5 mavsum", genre:"action", genreLabel:"Боевик / Triller", language:"O'zbek tilida", quality:"HD", type:"serial", isNew:true, poster:"https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg", desc:"Profesor rahbarligida bir guruh o'g'ri Ispaniya Milliy Bankini bosib olishni rejalashtiradi.", views:"3.8M", country:"Ispaniya", episodes:41 },
  { id:11, title:"The Lion King", year:2019, rating:6.9, duration:"1s 58d", genre:"cartoon", genreLabel:"Multfilm / Drama", language:"O'zbek tilida", quality:"HD", type:"cartoon", isNew:false, poster:"https://image.tmdb.org/t/p/w500/2bXbqYdUQNa0pE6RkFQn3doZt6m.jpg", desc:"Yosh sher Simba otasining o'limidan so'ng o'z vatanini tiklash uchun kuchli safarga chiqadi.", views:"1.1M", country:"AQSh" },
  { id:12, title:"Frozen 2", year:2019, rating:6.8, duration:"1s 43d", genre:"cartoon", genreLabel:"Multfilm / Musiqa", language:"O'zbek tilida", quality:"HD", type:"cartoon", isNew:false, poster:"https://image.tmdb.org/t/p/w500/qdfARIhgpgZOBh3vfNhWS4hmSo3.jpg", desc:"Elsa va Anna sehrli o'rmonning sirini kashf qilish uchun sayohatga chiqadilar.", views:"980K", country:"AQSh" },

  // ===== ANIME =====
  { id:13, title:"Attack on Titan", year:2013, rating:9.0, duration:"4 mavsum", genre:"action", genreLabel:"Anime / Боевик", language:"O'zbek tilida", quality:"HD", type:"anime", isNew:false, poster:"https://image.tmdb.org/t/p/w500/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg", videoId:"MGRm4IzK1SQ", desc:"Insonlar ulkan devorlar ortida titanlardan himoyalanib yashaydi. Eren Yeager esa titanlarni yo'q qilishga qasam ichadi.", views:"6.2M", country:"Yaponiya", episodes:87 },
  { id:14, title:"Naruto", year:2002, rating:8.3, duration:"5 mavsum", genre:"action", genreLabel:"Anime / Боевик / Fantastika", language:"O'zbek tilida", quality:"HD", type:"anime", isNew:false, poster:"https://image.tmdb.org/t/p/w500/xppeysfvDKVx775MFuH8Z9hyuC8.jpg", videoId:"rNcnBeFnHaw", desc:"Yosh ninja Naruto Uzumaki eng kuchli ninja — Hokage bo'lish orzusi bilan yashaydi. U ichidagi to'qqiz dumli tulki kuchidan foydalanishni o'rganadi.", views:"8.5M", country:"Yaponiya", episodes:720 },
  { id:15, title:"Death Note", year:2006, rating:9.0, duration:"1 mavsum", genre:"drama", genreLabel:"Anime / Triller / Drama", language:"O'zbek tilida", quality:"HD", type:"anime", isNew:false, poster:"https://image.tmdb.org/t/p/w500/iigTMBHFBpFJHhGTNvGlBwVVRAY.jpg", videoId:"NlJZ1ZgkrBg", desc:"Light Yagami sirli daftar topadi — unga istalgan odamning ismini yozsa, o'sha odam o'ladi. U dunyoni jinoyatlardan tozalashga qaror qiladi.", views:"7.1M", country:"Yaponiya", episodes:37 },
  { id:16, title:"One Piece", year:1999, rating:8.9, duration:"20+ mavsum", genre:"action", genreLabel:"Anime / Боевик / Sarguzasht", language:"O'zbek tilida", quality:"HD", type:"anime", isNew:false, poster:"https://image.tmdb.org/t/p/w500/fcXdJlB3873Bt4HkzRMFyR6EZBT.jpg", videoId:"S8_YwFLCh4U", desc:"Monkey D. Luffy gummi meva yeb, rezina tanaga ega bo'ladi. U afsonaviy xazina One Piece ni topish va dengiz qiroli bo'lish uchun sayohata chiqadi.", views:"9.3M", country:"Yaponiya", episodes:1000 },
  { id:17, title:"Demon Slayer", year:2019, rating:8.7, duration:"4 mavsum", genre:"action", genreLabel:"Anime / Боевик / Fantastika", language:"O'zbek tilida", quality:"UHD", type:"anime", isNew:true, poster:"https://image.tmdb.org/t/p/w500/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg", videoId:"VQGCKyvzIM4", desc:"Tanjiro Kamado oilasi iblislar tomonidan o'ldiriladi, singlisi esa iblisga aylanadi. U singlisini inson qilish uchun iblis qiruvchiga aylanadi.", views:"5.4M", country:"Yaponiya", episodes:55 },
  { id:18, title:"Fullmetal Alchemist: Brotherhood", year:2009, rating:9.1, duration:"1 mavsum", genre:"fantasy", genreLabel:"Anime / Fantastika / Sarguzasht", language:"O'zbek tilida", quality:"HD", type:"anime", isNew:false, poster:"https://image.tmdb.org/t/p/w500/5ZFUEOULaVml7pHj6nA4oJTgsIF.jpg", videoId:"--IcmZkvL0Q", desc:"Aka-uka Edward va Alphonse Elric onasini tiriltirishga urinib, kimyoviy sxema qoidasini buzadilar. Endi yo'qotganlarini qaytarish yo'lida safarga chiqadilar.", views:"4.8M", country:"Yaponiya", episodes:64 },
  { id:19, title:"Dragon Ball Z", year:1989, rating:8.7, duration:"9 mavsum", genre:"action", genreLabel:"Anime / Боевик / Fantastika", language:"O'zbek tilida", quality:"HD", type:"anime", isNew:false, poster:"https://image.tmdb.org/t/p/w500/oMChPOtWZmBFHXU8foTCZfvXwOt.jpg", videoId:"gFDFPL9CRNE", desc:"Son Goku va uning do'stlari Yer sayyorasini turli xavfli dushmanlardan himoya qiladilar. Har bir jangda ular yangi kuchlarni kashf etadilar.", views:"11.2M", country:"Yaponiya", episodes:291 },
  { id:20, title:"Tokyo Ghoul", year:2014, rating:7.8, duration:"4 mavsum", genre:"horror", genreLabel:"Anime / Dahshat / Drama", language:"O'zbek tilida", quality:"HD", type:"anime", isNew:false, poster:"https://image.tmdb.org/t/p/w500/gNbdjDi1HamTCrfvM9JeA94bNi2.jpg", videoId:"vGuQeQsoRgU", desc:"Ken Kaneki oddiy talaba edi, lekin xavfli ghoul bilan uchrashuv uni yarim ghoulga aylantiradi. Endi u ikkala dunyo o'rtasida yashashga majbur.", views:"3.7M", country:"Yaponiya", episodes:48 }
];
